version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - redis
    command: ["./api"]
  redis:
    image: redis
    ports:
      - "6379:6379"
